name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: App checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.5.0

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run format:check

      - name: Run linter
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run integration tests
        run: pnpm run test:integration

      - name: Typecheck
        run: pnpm run typecheck

      # Snyk could be a better alternative/addition
      - name: Run audit
        run: pnpm audit
